spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: flash-redis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
server:
  port: 7710

wechat:
  # 小程序appid
  app-id: "wx12756a2557e97544"
  # 小程序密钥
  app-secret: "你的小程序密钥"
  # 微信支付v3版密钥
  api-key3: "32位密钥"
  # 微信证书
  platform-cert-path: "wx_cert.pem"
  # 商家支付证书密钥
  key-path: "apiclient_key.pem"
  # 商家支付证书
  cert-path: "apiclient_cert.pem"
  # 商家支付证书 pkcs12格式
  cert-p12-path: "apiclient_cert.p12"
  # 商户id
  mch-id: "1619401626"
  # 支付回调地址
  notify-url: "https://www.jarcheng.top/testapi/order/notify"